method: ein_seld
dataset: dcase2020task3
workspace_dir: ./
dataset_dir: ./_dataset/dataset_root
hdf5_dir: ./_hdf5
data:
  type: foa
  sample_rate: 24000
  n_fft: 1024
  hop_length: 600
  n_mels: 256
  window: hann
  fmin: 20
  fmax: 12000
  train_chunklen_sec: 4
  train_hoplen_sec: 4
  test_chunklen_sec: 4
  test_hoplen_sec: 4
  audio_feature: logmel&intensity
  feature_freeze: True
data_augmentation: 
  type: None
training:
  train_id: EINV2_tPIT_n1
  model: EINV2
  resume_model: # None_epoch_latest.pth
  loss_type: all
  loss_beta: 0.5
  PIT_type: tPIT
  batch_size: 32
  train_fold: 2,3,4,5,6
  valid_fold: 1
  overlap: 1&2
  optimizer: adam
  lr: 0.0005
  lr_step_size: 80
  lr_gamma: 0.1
  max_epoch: 90
  threshold_sed: 0.5
  remark: None
inference:
  infer_id: EINV2_tPIT_n1
  testset_type: eval # dev | eval
  test_fold: None
  overlap: 1&2
  train_ids: EINV2_tPIT_n1
  models: EINV2
  batch_size: 64
  threshold_sed: 0.5
  remark: None
